/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pousada.View;

import br.com.pousada.Controller.ClienteController;
import br.com.pousada.Controller.FuncionarioController;
import br.com.pousada.Controller.HabitacaoController;
import br.com.pousada.Controller.LocacaoController;
import br.com.pousada.Controller.ReservaController;
import br.com.pousada.Model.Cliente;
import br.com.pousada.Model.Funcionario;
import br.com.pousada.Model.Habitacao;
import br.com.pousada.Model.Locacao;
import br.com.pousada.Model.Reserva;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guest01
 */
public class LocacaoCadastro extends javax.swing.JFrame {

    private JTable tabela;    
    private int linhaSelecionada;
    private DefaultTableModel modelo = new DefaultTableModel();

    public LocacaoCadastro(DefaultTableModel modelo) {        
        this.modelo = modelo;
        initComponents();
    }   
       

    public LocacaoCadastro() {
        this.modelo = new DefaultTableModel();       
        initComponents();
        carregarComboCliente();
        carregarComboFuncionario();
        carregarComboHabitacao();        
    }
    
    public LocacaoCadastro(int idLocacao){
        
         this.modelo = new DefaultTableModel();

        //***** Recuperar dados para Editar ***********************************************************        
        initComponents();

        ReservaController cc = new ReservaController();
        Reserva edit = cc.listId(idLocacao);

        //txCodigo.setText(Integer.toString(edit.getId()));
        txQuantidade.setText(Integer.toString(edit.getQuantidadereserva()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(edit.getDataEntrada());
        txDataEntrada.setText(data);

        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        String data1 = sdf1.format(edit.getDataSaida());
        txDataSaida.setText(data1);

        txNumPessoas.setText(Integer.toString(edit.getNumeroPessoas()));
        txValorLocacao.setText(Double.toString(edit.getValorReserva()));

        carregarComboCliente(edit.getCliente());
        carregarComboFuncionario(edit.getFuncionario());
        carregarComboHabitacao(edit.getHabitacao());
    }
    
    public LocacaoCadastro(DefaultTableModel modelo, int linhaSelecionada, int idLocacao) {
        this.modelo = new DefaultTableModel();

        //***** Recuperar dados para Editar *********************************************************** 
        this.modelo = modelo;        
        this.linhaSelecionada = linhaSelecionada;
        initComponents();

        LocacaoController cc = new LocacaoController();
        Locacao edit = cc.listId(idLocacao);

        txCodigo.setText(Integer.toString(edit.getId()));
        txQuantidade.setText(Integer.toString(edit.getQuantidadeLocacao()));

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String data = sdf.format(edit.getDataEntrada());
        txDataEntrada.setText(data);

        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        String data1 = sdf1.format(edit.getDataSaida());
        txDataSaida.setText(data1);

        txNumPessoas.setText(Integer.toString(edit.getNumeroPessoas()));
        txValorLocacao.setText(Double.toString(edit.getValorLocacao()));

        carregarComboCliente(edit.getCliente());
        carregarComboFuncionario(edit.getFuncionario());
        carregarComboHabitacao(edit.getHabitacao());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        txMargemLucro4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        ImagemLogo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btMenuPrincipal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txQuantidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txNumPessoas = new javax.swing.JTextField();
        cbHabitacao = new javax.swing.JComboBox();
        cbCliente = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txValorLocacao = new javax.swing.JTextField();
        cbFuncionario = new javax.swing.JComboBox();
        txDataEntrada = new javax.swing.JTextField();
        txDataSaida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        txMargemLucro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMargemLucro4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));

        painelLogin.setBackground(new java.awt.Color(204, 204, 204));
        painelLogin.setPreferredSize(new java.awt.Dimension(650, 150));

        ImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pousada/Imagens/logo.png"))); // NOI18N
        ImagemLogo.setText("jLabel4");

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("caDaSTro LOCaçÃo");

        btPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        btPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btLimpar.setForeground(new java.awt.Color(102, 102, 102));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btAdicionar.setBackground(new java.awt.Color(204, 204, 204));
        btAdicionar.setForeground(new java.awt.Color(102, 102, 102));
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btMenuPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        btMenuPrincipal.setForeground(new java.awt.Color(102, 102, 102));
        btMenuPrincipal.setText("Menu Aplicação");
        btMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addComponent(ImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addComponent(ImagemLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btLimpar)
                    .addComponent(btAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btMenuPrincipal)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Cliente.:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Dada de Saída.:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data de Entrada.:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Código.:");

        txCodigo.setEditable(false);
        txCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Habitação.:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Número de Pessoas.:");

        txQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txQuantidadeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Cadastrar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Quantidade.:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Funcionário.:");

        txNumPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumPessoasActionPerformed(evt);
            }
        });

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Valor da Reserva.:");

        txValorLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txValorLocacaoActionPerformed(evt);
            }
        });

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Consultar Reservas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txNumPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbHabitacao, 0, 144, Short.MAX_VALUE)
                                .addComponent(txDataEntrada))
                            .addGap(89, 89, 89)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txDataSaida))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbFuncionario, javax.swing.GroupLayout.Alignment.LEADING, 0, 144, Short.MAX_VALUE)
                        .addComponent(txValorLocacao, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbHabitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txDataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txNumPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txValorLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here: 

        //Codigo para Adicionar ao banco os Campos Preenchidos Cadastro 
        Locacao re = new Locacao();

        if (!(txCodigo.getText().equals("") || (txCodigo.getText() == null))) {
            re.setId(Integer.parseInt(txCodigo.getText()));
        }
        re.setCliente((Cliente) cbCliente.getSelectedItem());
        re.setFuncionario((Funcionario) cbFuncionario.getSelectedItem());
        re.setHabitacao((Habitacao) cbHabitacao.getSelectedItem());
        re.setQuantidadeLocacao(Integer.parseInt(txQuantidade.getText()));
        
        try {
            String data = txDataEntrada.getText();
            re.setDataEntrada(new SimpleDateFormat("dd/MM/yyyy").parse(data));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter a data");
        }
        try {
            String data = txDataSaida.getText();
            re.setDataSaida(new SimpleDateFormat("dd/MM/yyyy").parse(data));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao converter a data");
        }
        re.setNumeroPessoas(Integer.parseInt(txNumPessoas.getText()));
        re.setValorLocacao(Double.parseDouble(txValorLocacao.getText()));


        LocacaoController hc = new LocacaoController();
        if (re.getId() == 0) {
            int idLocacao = hc.save(re);
            if (idLocacao > 0) {
                JOptionPane.showMessageDialog(null, "Locação Cadastrada com Sucesso");
            }
        } else {
            int idLocacao = hc.save(re);
            if (idLocacao > 0) {
                JOptionPane.showMessageDialog(null, "Locação Cadastrada com Sucesso");
            }
        }
        //Construtor limpar campos
        limparDados();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
 
       // Estanciar Abertura da Janela Usuario
        LocacaoLista rl = new LocacaoLista();
        //Centrar Janela na abertura
        rl.setLocationRelativeTo(null);
        //Tornar Janela Visivel
        rl.setVisible(true);
        dispose();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoActionPerformed

    private void btMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuPrincipalActionPerformed
        // TODO add your handling code here:
        JanelaAplicacao ja = new JanelaAplicacao();
        ja.setLocationRelativeTo(null);
        ja.setVisible(true);
        dispose();
    }//GEN-LAST:event_btMenuPrincipalActionPerformed

    private void txQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txQuantidadeActionPerformed

    private void txNumPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumPessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumPessoasActionPerformed

    private void txMargemLucro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMargemLucro4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMargemLucro4ActionPerformed

    private void txValorLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txValorLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txValorLocacaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ClienteCadastro cc = new ClienteCadastro();
        cc.setLocationRelativeTo(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReservaListaLocacao cc = new ReservaListaLocacao();
        cc.setLocationRelativeTo(cc);
        cc.setVisible(true);
      
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemLogo;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btMenuPrincipal;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbHabitacao;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txDataEntrada;
    private javax.swing.JTextField txDataSaida;
    private javax.swing.JTextField txMargemLucro4;
    private javax.swing.JTextField txNumPessoas;
    private javax.swing.JTextField txQuantidade;
    private javax.swing.JTextField txValorLocacao;
    // End of variables declaration//GEN-END:variables

    private void limparDados() {
        // TODO add your handling code here:

        //Codigo para Limpar Campos de Preenchimento      
        txCodigo.setText("");
        txQuantidade.setText("");
        txNumPessoas.setText("");
        txValorLocacao.setText("");
        txDataEntrada.setText("");
        txDataSaida.setText("");
        txMargemLucro4.setText("");
       
    }

    private void carregarComboCliente() {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCliente.getModel();
        cbCliente.removeAllItems();

        //Buscar na base de dados os alunos cadastrados
        List<Cliente> clientes = new ArrayList<>();
        ClienteController cc = new ClienteController();
        clientes = cc.listAll();

        for (int linha = 0; linha < clientes.size(); linha++) {
            Cliente c = clientes.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(c);
        }     
    }

    private void carregarComboCliente(Cliente cliente) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCliente.getModel();
        cbCliente.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Cliente> clientes = new ArrayList<>();
        ClienteController cc = new ClienteController();
        clientes = cc.listAll();

        for (int linha = 0; linha < clientes.size(); linha++) {
            Cliente c = clientes.get(linha);
            comboModel.addElement(c);
            if (cliente.getId() == c.getId()) {
                comboModel.setSelectedItem(c);
            }
        }
    }

    private void carregarComboFuncionario() {
        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFuncionario.getModel();
        cbFuncionario.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Funcionario> funcionarios = new ArrayList<>();
        FuncionarioController ff = new FuncionarioController();
        funcionarios = ff.listAll();

        for (int linha = 0; linha < funcionarios.size(); linha++) {
            Funcionario f = funcionarios.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(f);
        }
    }

    private void carregarComboFuncionario(Funcionario funcionario) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFuncionario.getModel();
        cbFuncionario.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Funcionario> funcionarios = new ArrayList<>();
        FuncionarioController fc = new FuncionarioController();
        funcionarios = fc.listAll();

        for (int linha = 0; linha < funcionarios.size(); linha++) {
            Funcionario f = funcionarios.get(linha);
            comboModel.addElement(f);
            if (funcionario.getId() == f.getId()) {
                comboModel.setSelectedItem(f);
            }
        }
    }

    private void carregarComboHabitacao () {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbHabitacao.getModel();
        cbHabitacao.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Habitacao> habitacoes = new ArrayList<>();
        HabitacaoController hc = new HabitacaoController();
        habitacoes = hc.listAll();

        for (int linha = 0; linha < habitacoes.size(); linha++) {
            Habitacao ha = habitacoes.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(ha);
        }
    }

    private void carregarComboHabitacao(Habitacao habitacao) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbHabitacao.getModel();
        cbHabitacao.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Habitacao> habitacoes = new ArrayList<>();
        HabitacaoController hh = new HabitacaoController();
        habitacoes = hh.listAll();

        for (int linha = 0; linha < habitacoes.size(); linha++) {
            Habitacao h = habitacoes.get(linha);
            comboModel.addElement(h);
            if (habitacao.getId() == h.getId()) {
                comboModel.setSelectedItem(h);
            }
        }
    }
}
