/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pousada.View;

import br.com.pousada.Controller.ClienteController;
import br.com.pousada.Controller.FuncionarioController;
import br.com.pousada.Controller.LojaController;
import br.com.pousada.Controller.VendaController;
import br.com.pousada.Model.Cliente;
import br.com.pousada.Model.Funcionario;
import br.com.pousada.Model.Loja;
import br.com.pousada.Model.Venda;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author guest01
 */
public class LojaCadastro extends javax.swing.JFrame {

    private JTable tabela;
    private int linhaSelecionada;
    private DefaultTableModel modelo = new DefaultTableModel();

    public LojaCadastro(DefaultTableModel modelo) {
        this.modelo = modelo;
        initComponents();
    }
    

    public LojaCadastro() {
        initComponents();
        carregarComboCliente();
        carregarComboFuncionario();
        carregarComboVenda();
    }

    /**
     * Creates new form FuncionarioCadastro
     */
    public LojaCadastro(DefaultTableModel modelo, int linhaSelecionada, int idVenda) {

        //***** Recuperar dados para Editar *********************************************************** 
        this.modelo = modelo;
        this.linhaSelecionada = linhaSelecionada;
        initComponents();

       LojaController hc = new LojaController();
       Loja h = hc.listId(idVenda);

        txCodigo.setText(Integer.toString(h.getId()));
        txPagamento.setText(h.getFormaPagamento());
               
        carregarComboCliente(h.getCliente());
        carregarComboFuncionario(h.getFuncionario());
        carregarComboVenda(h.getVenda());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        ImagemLogo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btCadastroProdutos = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbVenda = new javax.swing.JComboBox();
        cbCliente = new javax.swing.JComboBox();
        txPagamento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbFuncionario = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 500));

        painelLogin.setBackground(new java.awt.Color(204, 204, 204));

        ImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pousada/Imagens/logo.png"))); // NOI18N
        ImagemLogo.setText("jLabel4");

        jLabel19.setFont(new java.awt.Font("Bauhaus 93", 0, 60)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("LOja");

        btPesquisar.setBackground(new java.awt.Color(204, 204, 204));
        btPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(204, 204, 204));
        btLimpar.setForeground(new java.awt.Color(102, 102, 102));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btAdicionar.setBackground(new java.awt.Color(204, 204, 204));
        btAdicionar.setForeground(new java.awt.Color(102, 102, 102));
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btCadastroProdutos.setBackground(new java.awt.Color(204, 204, 204));
        btCadastroProdutos.setForeground(new java.awt.Color(102, 102, 102));
        btCadastroProdutos.setText("Janela Aplicação");
        btCadastroProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLoginLayout = new javax.swing.GroupLayout(painelLogin);
        painelLogin.setLayout(painelLoginLayout);
        painelLoginLayout.setHorizontalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                .addComponent(ImagemLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLoginLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                                .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                            .addComponent(btCadastroProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addContainerGap())))
        );
        painelLoginLayout.setVerticalGroup(
            painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addComponent(ImagemLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisar)
                    .addComponent(btLimpar)
                    .addComponent(btAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadastroProdutos)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(650, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Produto.:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Forma de Pagamento.:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Código.:");

        txCodigo.setEditable(false);
        txCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodigoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Cliente.:");

        cbVenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Funcionário.:");

        cbFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVenda, 0, 452, Short.MAX_VALUE)
                    .addComponent(cbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txPagamento)
                    .addComponent(cbFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:

        //Codigo para Adicionar ao banco os Campos Preenchidos Cadastro habitaçao
       Loja h = new Loja();

        if (!(txCodigo.getText().equals("") || (txCodigo.getText() == null))) {
            h.setId(Integer.parseInt(txCodigo.getText()));
        }

        h.setFormaPagamento(txPagamento.getText());
       h.setCliente((Cliente) cbCliente.getSelectedItem());
        h.setFuncionario((Funcionario) cbFuncionario.getSelectedItem());
        h.setVenda((Venda) cbVenda.getSelectedItem());

        //Editar funcionario e endereço************************/**************************************

       LojaController fc = new LojaController();
        if (h.getId() == 0) {

            int idVenda = fc.save(h);
            if (idVenda > 0) {

                JOptionPane.showMessageDialog(null, "Venda Efetuada com sucesso");
            }
        } else {
            int idVenda = fc.save(h);
            if (idVenda > 0) {

                JOptionPane.showMessageDialog(null, "Venda Efetuada com sucesso");
            }
        }

        //Construtor limpar campos
        limparDados();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:

        //Estanciar Abertura da Janela Usuario
       LojaLista ho = new LojaLista();
        //Centrar Janela na abertura
        ho.setLocationRelativeTo(null);
        //Tornar Janela Visivel
        ho.setVisible(true);
        dispose();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void txCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodigoActionPerformed

    private void btCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroProdutosActionPerformed
        // TODO add your handling code here:
        JanelaAplicacao cp = new JanelaAplicacao();
        cp.setLocationRelativeTo(null);
        cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastroProdutosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemLogo;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btCadastroProdutos;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbFuncionario;
    private javax.swing.JComboBox cbVenda;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txPagamento;
    // End of variables declaration//GEN-END:variables

    private void limparDados() {
        // TODO add your handling code here:

        //Codigo para Limpar Campos de Preenchimento      
        txCodigo.setText("");
        txPagamento.setText("");           
    }
    
      private void carregarComboCliente() {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo

        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCliente.getModel();
        cbCliente.removeAllItems();

        //Buscar na base de dados os alunos cadastrados
        List<Cliente> clientes = new ArrayList<>();
        ClienteController cc = new ClienteController();
        clientes = cc.listAll();

        //Preencger o combo com os alunos que estao na lista

        for (int linha = 0; linha < clientes.size(); linha++) {
            Cliente c = clientes.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(c);
        }     
    }

    private void carregarComboCliente(Cliente cliente) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbCliente.getModel();
        cbCliente.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Cliente> clientes = new ArrayList<>();
        ClienteController cc = new ClienteController();
        clientes = cc.listAll();

        //Preencger o combo com os alunos que estao na lista

        for (int linha = 0; linha < clientes.size(); linha++) {
            Cliente c = clientes.get(linha);
            comboModel.addElement(c);
            if (cliente.getId() == c.getId()) {
                comboModel.setSelectedItem(c);
            }
        }
    }

    private void carregarComboFuncionario() {
        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFuncionario.getModel();
        cbFuncionario.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Funcionario> funcionarios = new ArrayList<>();
        FuncionarioController ff = new FuncionarioController();
        funcionarios = ff.listAll();

        //Preencger o combo com os alunos que estao na lista

        for (int linha = 0; linha < funcionarios.size(); linha++) {
            Funcionario f = funcionarios.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(f);
        }
    }

    private void carregarComboFuncionario(Funcionario funcionario) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbFuncionario.getModel();
        cbFuncionario.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Funcionario> funcionarios = new ArrayList<>();
        FuncionarioController fc = new FuncionarioController();
        funcionarios = fc.listAll();

        //Preencger o combo com os alunos que estao na lista

        for (int linha = 0; linha < funcionarios.size(); linha++) {
            Funcionario f = funcionarios.get(linha);
            comboModel.addElement(f);
            if (funcionario.getId() == f.getId()) {
                comboModel.setSelectedItem(f);
            }
        }
    }

    private void carregarComboVenda () {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbVenda.getModel();
        cbVenda.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Venda> vendas = new ArrayList<>();
        VendaController hh = new VendaController();
        vendas = hh.listAll();
       
        //Preencger o combo com os alunos que estao na lista

        for (int linha = 0; linha < vendas.size(); linha++) {
            Venda ha = vendas.get(linha);
            comboModel.setSelectedItem("  ----Selecione----  ");
            comboModel.addElement(ha);
        }
    }

    private void carregarComboVenda(Venda venda) {

        //Declarar uma varialvel
        //combodefaut para poder alterar dados do modelo
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) cbVenda.getModel();
        cbVenda.removeAllItems();
        //Buscar na base de dados os alunos cadastrados
        List<Venda> vendas = new ArrayList<>();
        VendaController hh = new VendaController();
        vendas = hh.listAll();

        //Preencher o combo com os alunos que estao na lista

        for (int linha = 0; linha < vendas.size(); linha++) {
            Venda h = vendas.get(linha);
            comboModel.addElement(h);
            if (venda.getId() == h.getId()) {
                comboModel.setSelectedItem(h);
            }
        }
    }

    
    
}
